export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const LOGOUT = 'LOGOUT';

export const DONORS_SUCCESS = 'DONORS_SUCCESS';
export const DONORS_FAIL = 'DONORS_FAIL';
export const DONOR_SEARCH_SUCCESS = 'DONOR_SEARCH_SUCCESS';
export const DONOR_SEARCH_FAIL = 'DONOR_SEARCH_FAIL';
export const ADD_DONOR_SUCCESS = 'ADD_DONOR_SUCCESS';
export const ADD_DONOR_FAIL = 'ADD_DONOR_FAIL';
export const EDIT_DONOR_SUCCESS = 'EDIT_DONOR_SUCCESS';
export const EDIT_DONOR_FAIL = 'EDIT_DONOR_FAIL';
export const DELETE_DONOR_SUCCESS = 'DELETE_DONOR_SUCCESS';
export const DELETE_DONOR_FAIL = 'DELETE_DONOR_FAIL';

export const COLLECTIONS_SUCCESS = 'COLLECTIONS_SUCCESS';
export const COLLECTIONS_FAIL = 'COLLECTIONS_FAIL';
export const COLLECTION_SEARCH_SUCCESS = 'COLLECTION_SEARCH_SUCCESS';
export const COLLECTION_SEARCH_FAIL = 'COLLECTION_SEARCH_FAIL';
export const ADD_COLLECTION_SUCCESS = 'ADD_COLLECTION_SUCCESS';
export const ADD_COLLECTION_FAIL = 'ADD_COLLECTION_FAIL';
export const EDIT_COLLECTION_SUCCESS = 'EDIT_COLLECTION_SUCCESS';
export const EDIT_COLLECTION_FAIL = 'EDIT_COLLECTION_FAIL';
export const DELETE_COLLECTION_SUCCESS = 'DELETE_COLLECTION_SUCCESS';
export const DELETE_COLLECTION_FAIL = 'DELETE_COLLECTION_FAIL';

export const COLLECTION_PHOTO_SUCCESS = 'COLLECTION_PHOTO_SUCCESS';
export const COLLECTION_PHOTO_FAIL = 'COLLECTION_PHOTO_FAIL';
export const OLD_PHOTO_DELETE_SUCCESS = 'OLD_PHOTO_DELETE_SUCCESS';
export const OLD_PHOTO_DELETE_FAIL = 'OLD_PHOTO_DELETE_FAIL';
export const OLD_PHOTO_DELETE_CANCEL = 'OLD_PHOTO_DELETE_CANCEL';